# Generated by Django 3.1.2 on 2020-10-18 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movement',
            name='end_picture',
        ),
        migrations.AlterField(
            model_name='movement',
            name='datetime',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date and Time'),
        ),
        migrations.AlterField(
            model_name='movement',
            name='start_picture',
            field=models.ImageField(upload_to='', verbose_name='Image'),
        ),
    ]
