# Generated by Django 3.1.2 on 2020-10-18 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20201018_1652'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movement',
            old_name='start_picture',
            new_name='img',
        ),
    ]
