# Generated by Django 3.1.2 on 2020-10-18 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_options'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Options',
            new_name='Option',
        ),
    ]
