# Generated by Django 3.1.2 on 2020-10-18 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20201018_1942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='option',
            name='key',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
